-- Arquivo de dados iniciais
-- Os dados de exemplo foram removidos temporariamente para evitar conflitos de schema
-- Para adicionar dados de teste, use a API REST ou o console H2 em http://localhost:8080/h2-console
